define(function(require, exports, module) {
	var FW = require("breeze/framework/js/BreezeFW");
	var resource = {
		"CMSMgrDefaultListControl":{
			"CMSMgrControl":require("./CMSMgrControlResource/CMSMgrControl.tpl")
		},
		"CMSMgrDefaultNodeDecorate":{
			"CMSMgrDefaultNodeResourceView":require("./CMSMgrDecoratesResource/CMSMgrDefaultNodeResourceView.tpl")
		},
		"CMSMgrDefaultTagDecorate":{
			"CMSMgrDefaultTagResourceView":require("./CMSMgrDecoratesResource/CMSMgrDefaultTagResourceView.tpl")
		},
		"CMSMgrDefaultListSearchDecorate":{
			"CMSMgrDefaultListSearchResourceView":require("./CMSMgrDecoratesResource/CMSMgrDefaultListSearchResourceView.tpl")
		},
		"CMSMgrDefaultListFilterDecorate":{
			"CMSMgrDefaultListFilterResourceView":require("./CMSMgrDecoratesResource/CMSMgrDefaultListFilterResourceView.tpl"),
			"configView":require("./CMSMgrDecoratesResource/CMSMgrDefaultListFilterConfigView.tpl")
		},
		"CMSMgrDefaultListViewDecorate":{
			"CMSMgrDefaultListViewResourceView":require("./CMSMgrDecoratesResource/CMSMgrDefaultListViewResourceView.tpl"),
			"CMSMgrDefaultMaskListViewResourceView":require("./CMSMgrDecoratesResource/CMSMgrDefaultMaskListViewResourceView.tpl"),
			"configView":require("./CMSMgrDecoratesResource/CMSMgrDefaultListConfigView.tpl")
		},
		"CMSMgrDefaultListPaginationDecorate":{
			"CMSMgrDefaultListPaginationResourceView":require("./CMSMgrDecoratesResource/CMSMgrDefaultListPaginationResourceView.tpl")
		},
		"CheckBox_Decorate":{
			"CheckBox_Decorate":require("../../CMSMgrTypeDecorate/resource/default/CheckBox_Decorate.tpl")
		},
		"DatePicker_Decorate":{
			"DatePicker_Decorate":require("../../CMSMgrTypeDecorate/resource/default/DatePicker_Decorate.tpl")
		},
		"DateTimePicker_Decorate":{
			"DateTimePicker_Decorate":require("../../CMSMgrTypeDecorate/resource/default/DateTimePicker_Decorate.tpl")
		},
		"Hidden_Decorate":{
			"Hidden_Decorate":require("../../CMSMgrTypeDecorate/resource/default/Hidden_Decorate.tpl")
		},
		"Html_Decorate":{
			"Html_Decorate":require("../../CMSMgrTypeDecorate/resource/default/Html_Decorate.tpl")
		},
		"Pics_Decorate":{
			"Pics_Decorate":require("../../CMSMgrTypeDecorate/resource/default/Pics_Decorate.tpl")
		},
		"File_Decorate":{
			"File_Decorate":require("../../CMSMgrTypeDecorate/resource/default/File_Decorate.tpl")
		},
		"Pic_Decorate":{
			"Pic_Decorate":require("../../CMSMgrTypeDecorate/resource/default/Pic_Decorate.tpl")
		},
		"CMSMgrDefaultHeaderDecorate":{
			"configView":require("./CMSMgrDecoratesResource/CMSMgrDefaultHeaderConfigView.tpl"),
			"CMSMgrDefaultHeaderResourceView":require("./CMSMgrDecoratesResource/CMSMgrDefaultHeaderResourceView.tpl")
		},
		"Radio_Decorate":{
			"Radio_Decorate":require("../../CMSMgrTypeDecorate/resource/default/Radio_Decorate.tpl")
		},
		"ReadOnly_Decorate":{
			"ReadOnly_Decorate":require("../../CMSMgrTypeDecorate/resource/default/ReadOnly_Decorate.tpl")
		},
		"Select_Decorate":{
			"Select_Decorate":require("../../CMSMgrTypeDecorate/resource/default/Select_Decorate.tpl")
		},
		"TextArea_Decorate":{
			"TextArea_Decorate":require("../../CMSMgrTypeDecorate/resource/default/TextArea_Decorate.tpl")
		},
		"Text_Decorate":{
			"Text_Decorate":require("../../CMSMgrTypeDecorate/resource/default/Text_Decorate.tpl")
		},
		"TimePicker_Decorate":{
			"TimePicker_Decorate":require("../../CMSMgrTypeDecorate/resource/default/TimePicker_Decorate.tpl")
		},
		"List_Decorate":{
			"List_Decorate":require("../../CMSMgrTypeDecorate/resource/default/List_Decorate.tpl")
		},
		"OuterLink_Decorate":{
			"OuterLink_Decorate":require("../../CMSMgrTypeDecorate/resource/default/OuterLink_Decorate.tpl")
		},
		"CMSMgrDefaultMaskControl":{
			"appMainView":require("./CMSMgrControlResource/CMSMgrMaskControl.tpl")
		},
		"CMSMgrDefaultSingleControl":{
			"appMainView":require("./CMSMgrControlResource/CMSMgrControl.tpl")
		},
		"CMSMgrDefaultSingleViewDecorate":{
			"CMSMgrDefaultSingleViewResourceView":require("./CMSMgrDecoratesResource/CMSMgrDefaultSingleViewResourceView.tpl"),
			"listShow":require("./CMSMgrControlResource/CMSMgrList.tpl"),
			"configView":require("./CMSMgrDecoratesResource/CMSMgrDefaultSingleConfigView.tpl")
		},
		"DateTimePicker":{
			"DatePicker_Decorate":require("../../CMSMgrTypeDecorate/resource/default/DatePicker_Decorate.tpl")
		},
		"CMSMgrModSingleControl":{
			"appMainView":require("./CMSMgrControlResource/CMSMgrControl.tpl"),
			"modListMaskView":require("./CMSMgrControlResource/CMSMgrModListMaskView.tpl")
		},
		"Info_Decorate":{
			"Info_Decorate":require("../../CMSMgrTypeDecorate/resource/default/Info_Decorate.tpl"),			
		},
		"Hidden_Decorate":{
			"Hidden_Decorate":require("../../CMSMgrTypeDecorate/resource/default/Hidden_Decorate.tpl")
		},
		"roleactiongroup_Control":{
			"groupView":require("./CMSMgrControlResource/roleactiongroup.tpl")
		},
		"CMSMgrDefaultListControl":{
			"debugView":require("./CMSMgrControlResource/debugpage.tpl")
		},
		"debugpage_Control":{
			"debugView":require("./CMSMgrControlResource/debugpage.tpl"),
			"debug4new":require("./CMSMgrControlResource/debugpage4new.tpl")
		}
	}
	FW.regResource(resource);
	return FW;
});
